version: '3'

services:
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
            #            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./laravel.conf:/etc/nginx/conf.d/default.conf
        #            - ./logs/nginx:/var/log/nginx
        depends_on:
            - app
        networks:
            - app-network

    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: your_mysql_root_password
            MYSQL_DATABASE: your_database_name
            MYSQL_USER: your_mysql_user
            MYSQL_PASSWORD: your_mysql_password
        ports:
            - "0.0.0.0:3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network

    app:
        build: .
        restart: always
        volumes:
            - .:/var/www/html
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: your_database_name
            DB_USERNAME: your_mysql_user
            DB_PASSWORD: your_mysql_password
            CLICKHOUSE_USERNAME: default
            CLICKHOUSE_PASSWORD: 1234
            CLICKHOUSE_PORT: 8123
            CLICKHOUSE_HOST: clickhouse
        networks:
            - app-network

    clickhouse:
        restart: always
        image: yandex/clickhouse-server
        ports:
            - "8123:8123"
            - "9000:9000"
        volumes:
            - clickhouse_data:/var/lib/clickhouse
        environment:
            - CLICKHOUSE_USER=default
            - CLICKHOUSE_PASSWORD=1234
        networks:
            - app-network

volumes:
    mysql-data:
    clickhouse_data:
    logs:
        driver: local

networks:
    app-network:
        driver: bridge
